# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

workspace 'Example.xcworkspace'

target 'ExampleSwift' do
  use_frameworks!
  project 'ExampleSwift/ExampleSwift.xcodeproj'
#  pod 'Masonry', '~> 1.1.0'
   pod 'BjmobSDK', :path => '../'
   #pod 'BjmobSDK', :git => 'https://github.com/bjmob/BjmobSDK.git', :tag => '0.0.37'
   # pod 'BjmobSDK', '0.0.38'

  pod 'Bugly'
end

target 'Example' do
  use_frameworks!
  project 'Example/Example.xcodeproj'
  pod 'Masonry', '~> 1.1.0'
  pod 'BjmobSDK', :path => '../'
  #pod 'BjmobSDK', :git => 'https://github.com/bjmob/BjmobSDK.git', :tag => '0.0.38'
  # pod 'BjmobSDK', '0.0.38'

end


post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
                  # 解决沙盒权限问题
                  config.build_settings['ENABLE_BITCODE'] = 'NO'
                  config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
                  config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
               end
          end
   end
end
